### ISSUE TITLE
Boost error in main.cpp

### ISSUE THREAD

**Issue by BenWoodford** [swlines/CIFReader#2]
[Line #229](https://github.com/swlines/CIFReader/blob/master/main.cpp#L229) still refers to

`````` .leaf()```
rather than
```.path().filename().c_str()```
``````

**Comment by swlines** [comment]
Oh dear. It appears I fail. Sorry!

Fixed in dfe6ad9 :)

**Comment by swlines** [comment]
I assume that everything is OK now? 

Tom

**Comment by BenWoodford** [comment]
Yup, all good. :)
